#!/usr/bin/env bash
# Copyright (C) 2015 Tomasz Przybył <fademind@gmail.com>
# Homepage: https://github.com/FadeMind/archbash
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
# 
# https://www.gnu.org/licenses/gpl.txt

bold=$(tput bold)
normal=$(tput sgr0)
redc=$(tput setaf 1)
yellowc=$(tput setaf 3)
FILESGIT=$(ls -1|grep git| cut -d '/' -f 1)

build() {
    #rm -rf _PKG/* &> /dev/null
    for p in $FILESGIT; do
        printf "${bold}BUILDING NEW VERSION ${redc}$p${normal}${bold} PACKAGE${normal}\n"
        cd $p
        makepkg -src &> /dev/null
        cp -r *.pkg.tar.xz ../_PKG/ &> /dev/null
        cd ..; done
    rm _PKG/{*bomi*,*kmail*,konqueror*,kfind*,keditbookmarks*,libkonq*,konq-plugins*,*smplayer*}.pkg.tar.xz &> /dev/null
    cp _PKG/*.pkg.tar.xz /var/cache/pacman/aur/
    find * -type f -name .SRCINFO -delete
    find * -type d -name src -exec rm -rf {} +
    find * -type d -name pkg -exec rm -rf {} +
    find * -type f -exec chmod 644 {} +
    find * -type d -exec chmod 755 {} +
}

src() {
    rm -rf _SRC/* &> /dev/null
    for p in $FILESGIT; do
        printf "${bold}BUILDING SRC TARBALL ${redc}$p${normal}${bold} PACKAGE${normal}\n"
        cd $p
        mkaurball &> /dev/null
        mv *.src.tar.gz ../_SRC/ &> /dev/null
        cd ..; done
    cd _SRC/
    cat *.src.tar.gz | tar -xvf - -i -z &> /dev/null && rm *.src.tar.gz 
    cd .. && find _SRC/ -type f -name '.SRCINFO' -delete
    rm -rf $HOME/dev/archpkgbuilds/AUR/packages-git/* &&  cp -r _SRC/* MENU $HOME/dev/archpkgbuilds/AUR/packages-git/ 
}

menu() {
    printf " ${redc}b${normal}   ${redc}build new packages (if available)${normal}\n"
    printf " ${redc}c${normal}   ${redc}cleanup subdirectories${normal}\n"
    printf " ${redc}s${normal}   ${redc}create new sources${normal}\n"
    printf " ${redc}fp${normal}  ${redc}open _PKG dir with packages${normal}\n"
    printf " ${redc}fs${normal}  ${redc}open _SRC dir with packages${normal}\n"
    printf " ${redc}pi${normal}  ${redc}install packages from _PKG directory${normal}\n"
    printf " ${yellowc}Any other key will close this menu${normal}\n"
    printf "select option and confirm via [ENTER]: "
    read SEL
        case "$SEL" in
            "b") build;tput clear;menu;;
            "c") find *-git -maxdepth 1 -mindepth 1 -type d -exec rm -rf {} \;;tput clear;menu;;
            "s") src;tput clear;menu;;
            "fp") xdg-open _PKG && tput clear && menu;;
            "fs") xdg-open _SRC && tput clear && menu;;
            #"pi") sudo pacman -U _PKG/*.pkg.tar.xz --noconfirm && tput clear && menu;;
            *) tput clear && exit 0;;
        esac
}

wget -q --spider http://google.com
if [ $? -eq 0 ]; then
    if [ "$(whoami)" == "root" ]; then
    printf "${redc}ERROR: Run this script as normal user!${normal}\n"
    exit 0
    else
        if [ "$FILESGIT" == " " ]; then
        printf "${redc}ERROR: GIT packages not found in this path!${normal}\n"
        exit 0
        else
            if [ ! -d _PKG ]; then
                mkdir -p _PKG
            fi
            if [ ! -d _SRC ]; then
                mkdir -p _SRC
            fi
            tput clear;menu
        fi
    fi
else
    printf "${redc}ERROR: Could not connect to internet!${normal}\n"
    exit 0
fi

